"use client";

// Shared Source Lens panel + type — used by both the Source Finder
// (when analysing search results) and the References tool (when
// viewing the analysis attached to a saved reference). Kept as a
// dumb presentational component: it just renders a result it's given,
// or a loading / error state.
//
// The analysis is generated by the convex action `sourceLens.analyse`.
// See convex/sourceLens.ts for the prompt that produces this shape.

import type { ReactNode } from "react";
import ToolChat from "./ToolChat";

export type LensResult = {
  relevance: { score: number; verdict: string };
  keyClaims: string[];
  quotablePhrases: string[];
  rubricFit: {
    criterion: string;
    howItHelps: string;
    confidence: "high" | "medium" | "low";
  }[];
  suggestedCitation: string;
  skipIfRubricRequires: string[];
  abstractLimitation: string;
};

// Tier 2 deep-read result is a SUPER-set of Tier 1 — it carries
// additional section-level breakdown when the AI had access to the
// full PDF, not just the abstract. Tier 1 callers can render this
// type too; the Tier 2 fields just won't be populated.
export type LensDeepResult = LensResult & {
  // True when this analysis was produced from the full paper text,
  // not just the abstract. UI uses this to suppress the
  // "abstract-only" caveat and surface page numbers.
  deepRead?: boolean;
  // Per-section relevance breakdown — IMRaD or whatever the paper used.
  sectionRelevance?: {
    section: string; // e.g. "Methods", "Discussion", "Results 3.2"
    relevance: "high" | "medium" | "low" | "skip";
    summary: string;
  }[];
  // Verbatim paragraph-level quotes with section context.
  paragraphQuotes?: {
    section: string;
    quote: string;
    whyItMatters: string;
  }[];
  // Full extracted PDF text, used by the in-app reader to render the
  // paper with highlights overlaid. Only present when the analysis
  // was produced from a Tier 2 Deep Read.
  extractedText?: string;
};

export function LensPanel(props: {
  running: boolean;
  result: LensDeepResult | undefined;
  error: string | undefined;
  hasAssignmentContext: boolean;
  // Optional slot to render extra controls (e.g. "Re-run" or "Copy")
  // in the panel header. Keeps the component flexible without adding
  // per-context props.
  headerExtras?: ReactNode;
}) {
  if (props.running) {
    return (
      <div className="mt-3 rounded-xl border border-violet-200 bg-violet-50/40 p-4 text-sm text-violet-900 dark:border-violet-900/40 dark:bg-violet-950/20 dark:text-violet-200">
        <div className="flex items-center gap-2" role="status" aria-label="Analysing this source">
          <svg
            className="h-3.5 w-3.5 animate-spin"
            xmlns="http://www.w3.org/2000/svg"
            fill="none"
            viewBox="0 0 24 24"
            aria-hidden
          >
            <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
            <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8v4a4 4 0 00-4 4H4z" />
          </svg>
          <span>Analysing this source against your assignment…</span>
        </div>
      </div>
    );
  }

  if (props.error) {
    return (
      <div className="mt-3 rounded-xl border border-rose-300 bg-rose-50 p-4 text-sm text-rose-800 dark:border-rose-800/60 dark:bg-rose-950/30 dark:text-rose-200">
        Lens couldn&apos;t analyse this source: {props.error}
      </div>
    );
  }

  if (!props.result) return null;

  const r = props.result;
  // Clamp to the 0-10 scale before any colour/badge logic — the AI can
  // occasionally return out-of-range scores.
  const relevanceScore = Math.min(10, Math.max(0, r.relevance.score));
  const scoreColor =
    relevanceScore >= 7
      ? "bg-emerald-100 text-emerald-800 dark:bg-emerald-950/60 dark:text-emerald-200"
      : relevanceScore >= 4
        ? "bg-amber-100 text-amber-800 dark:bg-amber-950/60 dark:text-amber-200"
        : "bg-rose-100 text-rose-800 dark:bg-rose-950/60 dark:text-rose-200";

  const confidenceColor: Record<"high" | "medium" | "low", string> = {
    high: "text-emerald-700 dark:text-emerald-300",
    medium: "text-amber-700 dark:text-amber-300",
    low: "text-slate-600 dark:text-slate-400",
  };

  const sectionRelevanceTone: Record<
    NonNullable<LensDeepResult["sectionRelevance"]>[number]["relevance"],
    string
  > = {
    high: "border-emerald-300 bg-emerald-50 text-emerald-900 dark:border-emerald-700/60 dark:bg-emerald-950/40 dark:text-emerald-200",
    medium: "border-sky-300 bg-sky-50 text-sky-900 dark:border-sky-700/60 dark:bg-sky-950/40 dark:text-sky-200",
    low: "border-slate-300 bg-slate-50 text-slate-800 dark:border-slate-700/60 dark:bg-slate-950/40 dark:text-slate-300",
    skip: "border-rose-300 bg-rose-50 text-rose-900 dark:border-rose-700/60 dark:bg-rose-950/40 dark:text-rose-200",
  };

  return (
    <>
    <div className="mt-3 space-y-3 rounded-xl border border-violet-200 bg-violet-50/40 p-4 text-sm dark:border-violet-900/40 dark:bg-violet-950/20">
      {/* Header: lens icon + relevance score + verdict */}
      <div className="flex flex-wrap items-baseline gap-2">
        <span className="text-base" aria-hidden>🔍</span>
        <span className="font-semibold uppercase tracking-wide text-xs text-violet-900 dark:text-violet-200">
          {r.deepRead ? "Source Lens · Deep read" : "Source Lens"}
        </span>
        <span
          className={`rounded-full px-2 py-0.5 text-xs font-medium ${scoreColor}`}
          title="0 = not relevant; 10 = strongly relevant"
        >
          Relevance {relevanceScore}/10
        </span>
        {!props.hasAssignmentContext && (
          <span className="rounded-full bg-slate-100 px-2 py-0.5 text-[11px] text-slate-600 dark:bg-slate-800 dark:text-slate-300">
            No assignment selected — generic analysis
          </span>
        )}
        {props.headerExtras && (
          <div className="ml-auto flex items-center gap-2">{props.headerExtras}</div>
        )}
      </div>
      <p className="text-slate-800 dark:text-slate-200">{r.relevance.verdict}</p>

      {/* Tier 2 only: per-section relevance map */}
      {r.sectionRelevance && r.sectionRelevance.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Section-by-section relevance
          </p>
          <ul className="mt-1 space-y-1">
            {r.sectionRelevance.map((s, i) => (
              <li
                key={i}
                className={`rounded-md border p-2 ${sectionRelevanceTone[s.relevance]}`}
              >
                <div className="flex items-baseline justify-between gap-2">
                  <span className="font-medium">{s.section}</span>
                  <span className="text-[11px] uppercase tracking-wide">
                    {s.relevance}
                  </span>
                </div>
                <p className="mt-0.5 text-xs leading-relaxed">{s.summary}</p>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Key claims */}
      {r.keyClaims.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Key claims {r.deepRead ? "(from full paper)" : "(from abstract)"}
          </p>
          <ul className="mt-1 list-disc space-y-0.5 pl-5 text-slate-800 dark:text-slate-200">
            {r.keyClaims.map((c, i) => (
              <li key={i}>{c}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Tier 2 only: paragraph-level verbatim quotes */}
      {r.paragraphQuotes && r.paragraphQuotes.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Paragraph-level quotes (verbatim from paper)
          </p>
          <ul className="mt-1 space-y-2">
            {r.paragraphQuotes.map((q, i) => (
              <li
                key={i}
                className="rounded-md border border-violet-200 bg-white p-2 dark:border-violet-900/60 dark:bg-slate-900"
              >
                <p className="text-[11px] font-medium uppercase tracking-wide text-violet-700 dark:text-violet-300">
                  {q.section}
                </p>
                <p className="mt-1 italic text-slate-900 dark:text-slate-100">
                  &ldquo;{q.quote}&rdquo;
                </p>
                <p className="mt-1 text-xs text-slate-600 dark:text-slate-400">
                  Why it matters: {q.whyItMatters}
                </p>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Quotable phrases (Tier 1 — abstract-level snippets) */}
      {r.quotablePhrases.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            {r.deepRead ? "Short quotable phrases" : "Quotable phrases"}
          </p>
          <ul className="mt-1 space-y-1 text-slate-900 dark:text-slate-100">
            {r.quotablePhrases.map((q, i) => (
              <li
                key={i}
                className="rounded-md border-l-2 border-violet-400 bg-white px-2 py-1 italic dark:border-violet-500 dark:bg-slate-900"
              >
                {q}
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Rubric fit */}
      {r.rubricFit.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Helps with these rubric criteria
          </p>
          <ul className="mt-1 space-y-1.5">
            {r.rubricFit.map((f, i) => (
              <li
                key={i}
                className="rounded-md border border-slate-200 bg-white p-2 dark:border-slate-800 dark:bg-slate-900"
              >
                <div className="flex items-baseline justify-between gap-2">
                  <span className="text-sm font-medium text-slate-900 dark:text-slate-100">
                    {f.criterion}
                  </span>
                  <span className={`text-[11px] uppercase tracking-wide ${confidenceColor[f.confidence]}`}>
                    {f.confidence} confidence
                  </span>
                </div>
                <p className="mt-0.5 text-xs text-slate-700 dark:text-slate-300">
                  {f.howItHelps}
                </p>
              </li>
            ))}
          </ul>
        </div>
      )}

      {/* Suggested in-text citation */}
      {r.suggestedCitation && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            Suggested in-text citation example
          </p>
          <p className="mt-1 rounded-md border border-slate-200 bg-white p-2 font-mono text-xs text-slate-800 dark:border-slate-800 dark:bg-slate-900 dark:text-slate-200">
            {r.suggestedCitation}
          </p>
        </div>
      )}

      {/* Skip-if list */}
      {r.skipIfRubricRequires.length > 0 && (
        <div>
          <p className="text-[11px] font-semibold uppercase tracking-wide text-slate-500 dark:text-slate-400">
            This source <em>doesn&apos;t</em> help with
          </p>
          <ul className="mt-1 list-disc space-y-0.5 pl-5 text-xs text-slate-600 dark:text-slate-400">
            {r.skipIfRubricRequires.map((s, i) => (
              <li key={i}>{s}</li>
            ))}
          </ul>
        </div>
      )}

      {/* Abstract-only caveat (only for Tier 1) */}
      {r.abstractLimitation && !r.deepRead && (
        <p className="rounded-md border border-amber-200 bg-amber-50 px-2 py-1.5 text-xs text-amber-900 dark:border-amber-900/40 dark:bg-amber-950/30 dark:text-amber-200">
          <span aria-hidden>⚠</span> {r.abstractLimitation}
        </p>
      )}
    </div>

    {/* Ask-about-this-paper chat — scoped to the lens analysis on screen */}
    <div className="mt-3">
      <ToolChat
        tool="sourceLens"
        title="Ask about this paper"
        suggestions={[
          "Is this source relevant to my assignment?",
          "What are the key findings?",
          "How would I cite this point?",
        ]}
        context={JSON.stringify(r, null, 2)}
      />
    </div>
    </>
  );
}

// Utility: build a copy-as-markdown representation of a Lens result.
// Shared between Source Finder and References so the format is
// consistent across copy buttons.
export function lensResultToMarkdown(r: LensDeepResult, title?: string): string {
  const lines: string[] = [];
  lines.push(`# Source Lens analysis${title ? ` — ${title}` : ""}`);
  lines.push("");
  lines.push(
    `**Relevance: ${r.relevance.score}/10** ${r.deepRead ? "(deep read of full paper)" : "(based on abstract)"}`,
  );
  lines.push(r.relevance.verdict);
  if (r.sectionRelevance && r.sectionRelevance.length > 0) {
    lines.push("\n## Section-by-section relevance\n");
    for (const s of r.sectionRelevance) {
      lines.push(`- **${s.section}** (${s.relevance}) — ${s.summary}`);
    }
  }
  if (r.keyClaims.length > 0) {
    lines.push("\n## Key claims\n");
    for (const c of r.keyClaims) lines.push(`- ${c}`);
  }
  if (r.paragraphQuotes && r.paragraphQuotes.length > 0) {
    lines.push("\n## Paragraph quotes\n");
    for (const q of r.paragraphQuotes) {
      lines.push(`**${q.section}:** "${q.quote}"`);
      lines.push(`*Why it matters: ${q.whyItMatters}*\n`);
    }
  }
  if (r.quotablePhrases.length > 0) {
    lines.push("\n## Quotable phrases\n");
    for (const q of r.quotablePhrases) lines.push(`> ${q}`);
  }
  if (r.rubricFit.length > 0) {
    lines.push("\n## Rubric fit\n");
    for (const f of r.rubricFit) {
      lines.push(`- **${f.criterion}** (${f.confidence} confidence): ${f.howItHelps}`);
    }
  }
  if (r.suggestedCitation) {
    lines.push("\n## Suggested citation\n");
    lines.push(r.suggestedCitation);
  }
  if (r.skipIfRubricRequires.length > 0) {
    lines.push("\n## Doesn't help with\n");
    for (const s of r.skipIfRubricRequires) lines.push(`- ${s}`);
  }
  if (r.abstractLimitation && !r.deepRead) {
    lines.push(`\n_⚠ ${r.abstractLimitation}_`);
  }
  return lines.join("\n");
}
